### ISSUE TITLE
Share the DarkSky API call part

### ISSUE THREAD

**Issue by bdthemes** [cartond/flat-weather-darksky-port.js#2]
Hi, I have it's license and they did not update script and now he deleted his project from codecanyon 😞 

I follow your doc and updated the js part, Can you tell me how i call the Darksky api part? Can you share your API call part?

**Comment by cartond** [comment]
I did see he deleted that script - great...

Anyways, as I mention in the comments, you have to build your own backend to call DarkSky's API. If you find another free API, I'm happy to help build it out to work with that flat weather.

No, I cannot share my backend to others.

**Comment by bdthemes** [comment]
Hi @cartond, Thanks for your reply. I already start to building new widget with apixu.com api it's also a good free alternative of yahoo/openweather api.

**Comment by cartond** [comment]
Let me know if you want help!
